#if !canImport(ObjectiveC)
import XCTest

extension ReflectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReflectionTests = [
        ("testMeasureMirrorReflectingDescriptionClass", testMeasureMirrorReflectingDescriptionClass),
        ("testMeasureMirrorReflectingDescriptionEnum", testMeasureMirrorReflectingDescriptionEnum),
        ("testMeasureMirrorReflectingDescriptionStruct", testMeasureMirrorReflectingDescriptionStruct),
        ("testMeasureStringDescribingClass", testMeasureStringDescribingClass),
        ("testMeasureStringDescribingEnum", testMeasureStringDescribingEnum),
        ("testMeasureStringDescribingStruct", testMeasureStringDescribingStruct),
        ("testMeasureStringIterpolationClass", testMeasureStringIterpolationClass),
        ("testMeasureStringIterpolationEnum", testMeasureStringIterpolationEnum),
        ("testMeasureStringIterpolationStruct", testMeasureStringIterpolationStruct),
        ("testMeasureStringReflectingClass", testMeasureStringReflectingClass),
        ("testMeasureStringReflectingEnum", testMeasureStringReflectingEnum),
        ("testMeasureStringReflectingStruct", testMeasureStringReflectingStruct),
        ("testMeasureTypeNameClass", testMeasureTypeNameClass),
        ("testMeasureTypeNameEnum", testMeasureTypeNameEnum),
        ("testMeasureTypeNameStruct", testMeasureTypeNameStruct),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReflectionTests.__allTests__ReflectionTests),
    ]
}
#endif
