name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ["12_beta"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test -c release -v --skip-update --enable-test-discovery
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test -c release -v --skip-update --enable-test-discovery
